apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: kubia
  name: kubia
spec:
  replicas: 3
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
