apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-1
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: "/var/log/nginx"
        name: my-awesome-logs

  volumes:
    - name: my-awesome-logs
      persistentVolumeClaim:
        claimName: my-awesome-pvc

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-2
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: "/var/log/nginx"
        name: my-awesome-logs

  volumes:
    - name: my-awesome-logs
      persistentVolumeClaim:
        claimName: my-awesome-pvc

