apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-3
  labels:
    app: nginx # <--- Très important pour l'anti-affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx
        topologyKey: "kubernetes.io/hostname"
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: "/var/log/nginx"
        name: my-awesome-logs
  volumes:
    - name: my-awesome-logs
      persistentVolumeClaim:
        claimName: my-awesome-pvc
