apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bob
rules:
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create"]

  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    resourceNames: ["bob"]
    verbs: ["get", "create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bob
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: rbac
