apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kubia-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: kubia
  updatePolicy:
    updateMode: "Recreate"

