server {
    listen 80;
    server_name www.kubia-example.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.kubia-example.com;

    ssl_certificate     certs/https.cert;
    ssl_certificate_key certs/https.key;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
